services:
  docs:
    image: lahomes_django_local_docs
    container_name: lahomes_django_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./lahomes_django:/app/lahomes_django:z
    ports:
      - '9000:9000'
    command: /start-docs
