# Generated by Django 5.0.9 on 2026-08-27 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Agente')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador / Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('command', models.CharField(help_text='Comando ou módulo python a ser executado', max_length=255, verbose_name='Comando / Script')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Em Execução'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='PENDING', max_length=20, verbose_name='Status')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload de Entrada')),
                ('output_result', models.JSONField(blank=True, default=dict, verbose_name='Resultado / Output')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agents.agent', verbose_name='Agente')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_executions', to=settings.AUTH_USER_MODEL, verbose_name='Disparado por')),
            ],
            options={
                'verbose_name': 'Log de Execução',
                'verbose_name_plural': 'Logs de Execução',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Integração')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='Token Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='agents.agent', verbose_name='Agente Destino')),
            ],
            options={
                'verbose_name': 'Integração Webhook',
                'verbose_name_plural': 'Integrações Webhook',
            },
        ),
    ]
